services:
  api:
    image: keanp89/ab_inbev_api
    container_name: ab_inbev_api_8505

    environment:
      - MONGO_URI=mongodb://mongo:27017
    
    build:
      context: ./api
      dockerfile: Dockerfile

    ports:
      - 8505:8505

    working_dir: /code/
    command: uvicorn app:app --port 8505 --host 0.0.0.0 --reload --workers 4
    # command: gunicorn app:app --workers 4 --worker-class uvicorn.workers.UvicornWorker --bind 0.0.0.0:8108 --log-level debug

    depends_on:
      - mongo

    tty: true

    networks:
      - project_network

    volumes:
      - ./api/:/code/

    restart: on-failure

  frontend:
    image: keanp89/streamlit_front
    container_name: streamlit_app_8504
    
    build:
      context: ./frontend
      dockerfile: Dockerfile

    ports:
      - 8504:8504

    working_dir: /front_code/
    command: streamlit run st_front.py --server.port 8504
 
    networks:
      - project_network

    depends_on:
      - api

    volumes:
      - ./frontend/:/front_code/

  mongo:
    image: mongo
    container_name: mongo-db

    tty: true

    networks:
      - project_network

    volumes:
      - ./db:/data/db

networks:
  project_network: